name: ğŸš€ Deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest

    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2

    - name: ğŸ“ Set environment variables
      run: |
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
        echo "VITE_URL=${{ secrets.VITE_URL }}" >> .env
        
    - name: ğŸ”§ Install dependencies and build
      run: |
        npm install
        npm run build

    - name: ğŸ“‚ Set up SSH key for deployment
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: ğŸ› ï¸ Add server to known_hosts
      run: ssh-keyscan -H ${{ secrets.SERVER }} >> ~/.ssh/known_hosts

    - name: ğŸ—‘ï¸ Remove old files on server
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.SERVER }} "rm -rf /home/iddemomorin/htdocs/demo.morin.id.vn/*"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: ğŸš€ Deploy via SSH
      run: |
        rsync -avz --no-perms --omit-dir-times dist/ ${{ secrets.USER }}@${{ secrets.SERVER }}:/home/iddemomorin/htdocs/demo.morin.id.vn
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
